### ISSUE TITLE
what is the license for this code? 

### ISSUE THREAD

**Issue by jaidevjoshi83** [vagkaratzas/PathWalks#1]
what is the license for this code?

**Comment by vagkaratzas** [comment]
This is a no-license repository. However, you are allowed to modify and redistribute the PathWalks code freely.

**Comment by jaidevjoshi83** [comment]
Hello, thanks for your reply, for sharing awesome work with the community, and for allowing me to modify and redistribute the code. However, the project in which I m working requires clarity about the license. If you. don't have any specific concerns and want to make your code open source please add a license file that contains one of the open sources licenses (ex. MIT). I will open a pull request to this repo with an MIT license file feel free to merge the pull request if you find it appropriate for your code so that community can use your code without any restriction. 

 thanks.

This is the Github guideline that restricts users to modify and redistribute the codes that do not have a proper license file.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
You’re under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you’re creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by vagkaratzas** [comment]
A "GNU AFFERO GENERAL PUBLIC LICENSE" has now been added to the project.

**Comment by jaidevjoshi83** [comment]
Thanks a lot, I highly appreciate this.
